name: 'Reusable Workflow: Deploy Roles'

on:
  workflow_call:
    inputs:
      pacEnvironmentSelector:
        required: true
        type: string
      planGitHubEnvironment:
        required: true
        type: string
      PAC_INPUT_FOLDER:
        required: true
        type: string
      PAC_DEFINITIONS_FOLDER:
        required: true
        type: string

env:
  PAC_INPUT_FOLDER: ${{ inputs.PAC_INPUT_FOLDER }}
  PAC_DEFINITIONS_FOLDER: ${{ inputs.PAC_DEFINITIONS_FOLDER }}

jobs:
  deployRoles:
    runs-on: ubuntu-latest
    environment: ${{ inputs.planGitHubEnvironment }}
    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4

      - name: Download Artifact
        # If you are using GHES, use v3 instead of v4. See https://github.com/actions/download-artifact#v4---whats-new for more information.
        uses: actions/download-artifact@d3f86a106a0bac45b974a628896c90dbdf5c8093 # v4
        with:
          name: plans-${{ inputs.pacEnvironmentSelector }}
          path: ${{ inputs.PAC_INPUT_FOLDER }}

      - name: Install Required Modules
        uses: Azure/powershell@53dd145408794f7e80f97cfcca04155c85234709 # v2
        with:
          inlineScript: |
            Install-Module EnterprisePolicyAsCode -Force
          azPSVersion: "latest"

      - name: Azure Login
        uses: azure/login@a457da9ea143d694b1b9c7c869ebb04ebe844ef5 # v2
        with:
          client-id: ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_TENANT_ID }}
          enable-AzPSSession: true
          allow-no-subscriptions: true

      - name: Deploy Roles
        uses: azure/powershell@53dd145408794f7e80f97cfcca04155c85234709 # v2
        with:
          inlineScript: |
            Deploy-RolesPlan -PacEnvironmentSelector ${{ inputs.pacEnvironmentSelector }} -InformationAction Continue
          azPSVersion: "latest"