# This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
name: EPAC Production Workflow

on:
  pull_request:
    branches:
      - main
    types:
      - closed
    paths:
      - 'EPAC-Definitions/contoso-lab/**'

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./EPAC-Definitions/contoso-lab

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan Production
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: contoso-prod
      planGitHubEnvironment: EPAC-PROD-PLAN
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./EPAC-Definitions/contoso-lab
    secrets: inherit

  deployPolicy:
    name: Deploy Production Policy Changes
    needs: plan
    if: needs.plan.outputs.deployPolicyChanges == 'yes' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-policy.yml
    with:
      pacEnvironmentSelector: contoso-prod
      planGitHubEnvironment: EPAC-PROD-DEPLOY
      PAC_INPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./EPAC-Definitions/contoso-lab
    secrets: inherit

  deployRoles:
    name: Deploy Production Role Changes
    needs: plan
    if: needs.plan.outputs.deployRoleChanges == 'yes' && github.ref == 'refs/heads/main'
    uses: ./.github/workflows/deploy-roles.yml
    with:
      pacEnvironmentSelector: contoso-prod
      planGitHubEnvironment: EPAC-PROD-DEPLOY
      PAC_INPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./EPAC-Definitions/contoso-lab
    secrets: inherit