# This pipeline is used to deploy Policies, Initiative definitions and Assignments into Azure.
name: EPAC Sandbox Workflow

on:
  push:
    branches:
      - feature/**
    paths:
      - "Definitions/**"
      - ".github/**"
  workflow_dispatch:

env:
  PAC_OUTPUT_FOLDER: ./Output
  PAC_DEFINITIONS_FOLDER: ./Definitions

permissions:
  contents: read
  id-token: write

jobs:
  plan:
    name: Plan epac-sandbox
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: contoso-sandbox
      planGitHubEnvironment: EPAC-SANDBOX
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployPolicy:
    name: Deploy epac-sandbox Policy Changes
    needs: plan
    if: needs.plan.outputs.deployPolicyChanges == 'yes'
    uses: ./.github/workflows/deploy-policy.yml
    with:
      pacEnvironmentSelector: contoso-sandbox
      planGitHubEnvironment: EPAC-SANDBOX
      PAC_INPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  deployRoles:
    name: Deploy epac-sandbox Role Changes
    needs: plan
    if: needs.plan.outputs.deployRoleChanges == 'yes'
    uses: ./.github/workflows/deploy-roles.yml
    with:
      pacEnvironmentSelector: contoso-sandbox
      planGitHubEnvironment: EPAC-SANDBOX
      PAC_INPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit

  tenantPlan:
    name: Plan prod
    needs: [deployPolicy, deployRoles]
    if: |
      always()
      && !contains(needs.*.result,'failure')
    uses: ./.github/workflows/plan.yml
    with:
      pacEnvironmentSelector: contoso-prod
      planGitHubEnvironment: EPAC-PROD-PLAN
      PAC_OUTPUT_FOLDER: ./Output
      PAC_DEFINITIONS_FOLDER: ./Definitions
    secrets: inherit
